// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>MyScript</b><br>
 * Generated     : <b>2012/06/18 10:01:14 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  June 18, 2012
 * @author paramveer.singh
 */
public abstract class MyScriptHelper extends RFTPackage.RFTlibclass
{
	/**
	 * Enquiry: with default state.
	 *		.text : Enquiry
	 * 		.id : 
	 * 		.href : javascript:void(0);
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_enquiry() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_enquiry"));
	}
	/**
	 * Enquiry: with specific test context and state.
	 *		.text : Enquiry
	 * 		.id : 
	 * 		.href : javascript:void(0);
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_enquiry(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_enquiry"), anchor, flags);
	}
	
	/**
	 * typeR: with default state.
	 *		.id : domRndWay
	 * 		.type : radio
	 * 		.value : R
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : type
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject radioButton_typeR() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_typeR"));
	}
	/**
	 * typeR: with specific test context and state.
	 *		.id : domRndWay
	 * 		.type : radio
	 * 		.value : R
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : type
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject radioButton_typeR(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_typeR"), anchor, flags);
	}
	
	/**
	 * datePickerDepart_dom1: with default state.
	 *		.id : datePickerDepart_dom1
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : datePickerDepart_dom1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_datePickerDepart_dom1() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_datePickerDepart_dom1"));
	}
	/**
	 * datePickerDepart_dom1: with specific test context and state.
	 *		.id : datePickerDepart_dom1
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : datePickerDepart_dom1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_datePickerDepart_dom1(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_datePickerDepart_dom1"), anchor, flags);
	}
	
	/**
	 * q: with default state.
	 *		.id : gbqfq
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : q
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_q() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_q"));
	}
	/**
	 * q: with specific test context and state.
	 *		.id : gbqfq
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : q
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_q(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_q"), anchor, flags);
	}
	
	

	protected MyScriptHelper()
	{
		setScriptName("MyScript");
	}
	
}

