//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.06 at 07:24:26 PM IST 
//

package com.plugin.appium;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ParentProperties" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Src" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ParentURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Index" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "parentProperties" })
@XmlRootElement(name = "ArrayOfParentProperties")
public class ArrayOfParentProperties {

	@XmlElement(name = "ParentProperties")
	protected List<ArrayOfParentProperties.ParentProperties> parentProperties;

	/**
	 * Gets the value of the parentProperties property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the parentProperties property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getParentProperties().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ArrayOfParentProperties.ParentProperties }
	 * 
	 * 
	 */
	public List<ArrayOfParentProperties.ParentProperties> getParentProperties() {
		if (parentProperties == null) {
			parentProperties = new ArrayList<ArrayOfParentProperties.ParentProperties>();
		}
		return this.parentProperties;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="Src" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="ParentURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="Tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="Index" type="{http://www.w3.org/2001/XMLSchema}integer"/>
	 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "type", "url", "src", "parentURL", "tag", "index", "name", "title", "id" })
	public static class ParentProperties {

		@XmlElement(name = "Type", required = true)
		protected String type;
		@XmlElement(name = "URL", required = true)
		protected String url;
		@XmlElement(name = "Src", required = true)
		protected String src;
		@XmlElement(name = "ParentURL", required = true)
		protected String parentURL;
		@XmlElement(name = "Tag", required = true)
		protected String tag;
		@XmlElement(name = "Index")
		protected int index;
		@XmlElement(name = "Name", required = true)
		protected String name;
		@XmlElement(name = "Title", required = true)
		protected String title;
		@XmlElement(name = "Id", required = true)
		protected String id;

		/**
		 * Gets the value of the type property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getType() {
			return type;
		}

		/**
		 * Sets the value of the type property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setType(String value) {
			this.type = value;
		}

		/**
		 * Gets the value of the url property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getURL() {
			return url;
		}

		/**
		 * Sets the value of the url property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setURL(String value) {
			this.url = value;
		}

		/**
		 * Gets the value of the src property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSrc() {
			return src;
		}

		/**
		 * Sets the value of the src property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSrc(String value) {
			this.src = value;
		}

		/**
		 * Gets the value of the parentURL property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getParentURL() {
			return parentURL;
		}

		/**
		 * Sets the value of the parentURL property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setParentURL(String value) {
			this.parentURL = value;
		}

		/**
		 * Gets the value of the tag property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getTag() {
			return tag;
		}

		/**
		 * Sets the value of the tag property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setTag(String value) {
			this.tag = value;
		}

		/**
		 * Gets the value of the index property.
		 * 
		 */
		public int getIndex() {
			return index;
		}

		/**
		 * Sets the value of the index property.
		 * 
		 */
		public void setIndex(int value) {
			this.index = value;
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setName(String value) {
			this.name = value;
		}

		/**
		 * Gets the value of the title property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getTitle() {
			return title;
		}

		/**
		 * Sets the value of the title property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setTitle(String value) {
			this.title = value;
		}

		/**
		 * Gets the value of the id property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getId() {
			return id;
		}

		/**
		 * Sets the value of the id property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setId(String value) {
			this.id = value;
		}

	}

}
